INSERT INTO Breakpoints
(GUIDELINES, [YEAR], TEST_METHOD, POTENCY, ORGANISM_CODE, ORGANISM_CODE_TYPE, BREAKPOINT_TYPE,
	HOST, SITE_OF_INFECTION, REFERENCE_TABLE, REFERENCE_SEQUENCE, WHONET_ABX_CODE, WHONET_TEST,
	R, I, S, DATE_ENTERED)
SELECT CASE WHEN GUIDELINES = 'CLSI22' THEN 'CLSI' ELSE 'EUCAST' END AS GUIDELINES,
	'2022' AS [YEAR],
	TESTMETHOD AS TEST_METHOD,
	POTENCY,
	ORG_CODE AS ORGANISM_CODE,
	CASE WHEN lower(ORG_CODE) = ORG_CODE THEN 'WHONET_ORG_CODE' ELSE NULL END AS ORGANISM_CODE_TYPE,
	BREAKPOINT_TYPE,
	HOST,
	SITE_INF AS SITE_OF_INFECTION,
	REF_TABLE AS REFERENCE_TABLE,
	REF_SEQ AS REFERENCE_SEQUENCE,
	WHON5_CODE AS WHONET_ABX_CODE,
	WHON5_TEST AS WHONET_TEST,
	CASE WHEN TESTMETHOD = 'DISK' THEN DISK_R ELSE MIC_R END AS R,
	CASE WHEN TESTMETHOD = 'DISK' THEN DISK_I ELSE NULL END AS I,
	CASE WHEN TESTMETHOD = 'DISK' THEN DISK_S ELSE MIC_S END AS S,
	'2022-01-01' AS DATE_ENTERED
FROM BP2022
WHERE GUIDELINES = 'CLSI22' OR GUIDELINES = 'EUCST22'